#!/bin/bash

# Load environment variables from .env file
if [ -f dev.env ]
then
    export $(cat dev.env | sed 's/"//g; s/'\''//g' | xargs)
    # Print all environment variables
    echo "Environment variables loaded from dev.env"
    echo "========================================"
    echo "DB_DATABASE: $DB_DATABASE"
    echo "DB_HOST: $DB_HOST"
    echo "DB_USERNAME: $DB_USERNAME"
    echo "DB_PASSWORD: $DB_PASSWORD"
    echo "DB_PORT: $DB_PORT"
    echo "========================================"
fi

function drop_all_tables() {
    export PGPASSWORD=$DB_PASSWORD
    echo "Dropping all tables in database: $DB_DATABASE"
    echo "Connecting to host: $DB_HOST"
    echo "Connecting with user: $DB_USERNAME" 
    if [ -z "$DB_DATABASE" ] || [ -z "$DB_HOST" ] || [ -z "$DB_USERNAME" ]; then
        echo "One or more variables are undefined. Exiting."
        exit 1
    fi
    psql -h $DB_HOST -U $DB_USERNAME -d $DB_DATABASE -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public;'
    echo "All tables dropped."
}

drop_all_tables
